# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jan/Documents/GitHub/abledecoder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jan/Documents/GitHub/abledecoder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jan/Documents/GitHub/abledecoder/CMakeFiles /Users/jan/Documents/GitHub/abledecoder//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jan/Documents/GitHub/abledecoder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abledecoder

# Build rule for target.
abledecoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 abledecoder
.PHONY : abledecoder

# fast build rule for target.
abledecoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/build
.PHONY : abledecoder/fast

AbleChunk.o: AbleChunk.cpp.o
.PHONY : AbleChunk.o

# target to build an object file
AbleChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/AbleChunk.cpp.o
.PHONY : AbleChunk.cpp.o

AbleChunk.i: AbleChunk.cpp.i
.PHONY : AbleChunk.i

# target to preprocess a source file
AbleChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/AbleChunk.cpp.i
.PHONY : AbleChunk.cpp.i

AbleChunk.s: AbleChunk.cpp.s
.PHONY : AbleChunk.s

# target to generate assembly for a file
AbleChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/AbleChunk.cpp.s
.PHONY : AbleChunk.cpp.s

CommonChunk.o: CommonChunk.cpp.o
.PHONY : CommonChunk.o

# target to build an object file
CommonChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/CommonChunk.cpp.o
.PHONY : CommonChunk.cpp.o

CommonChunk.i: CommonChunk.cpp.i
.PHONY : CommonChunk.i

# target to preprocess a source file
CommonChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/CommonChunk.cpp.i
.PHONY : CommonChunk.cpp.i

CommonChunk.s: CommonChunk.cpp.s
.PHONY : CommonChunk.s

# target to generate assembly for a file
CommonChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/CommonChunk.cpp.s
.PHONY : CommonChunk.cpp.s

FileChunk.o: FileChunk.cpp.o
.PHONY : FileChunk.o

# target to build an object file
FileChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FileChunk.cpp.o
.PHONY : FileChunk.cpp.o

FileChunk.i: FileChunk.cpp.i
.PHONY : FileChunk.i

# target to preprocess a source file
FileChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FileChunk.cpp.i
.PHONY : FileChunk.cpp.i

FileChunk.s: FileChunk.cpp.s
.PHONY : FileChunk.s

# target to generate assembly for a file
FileChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FileChunk.cpp.s
.PHONY : FileChunk.cpp.s

FormChunk.o: FormChunk.cpp.o
.PHONY : FormChunk.o

# target to build an object file
FormChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FormChunk.cpp.o
.PHONY : FormChunk.cpp.o

FormChunk.i: FormChunk.cpp.i
.PHONY : FormChunk.i

# target to preprocess a source file
FormChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FormChunk.cpp.i
.PHONY : FormChunk.cpp.i

FormChunk.s: FormChunk.cpp.s
.PHONY : FormChunk.s

# target to generate assembly for a file
FormChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FormChunk.cpp.s
.PHONY : FormChunk.cpp.s

FormatVersionChunk.o: FormatVersionChunk.cpp.o
.PHONY : FormatVersionChunk.o

# target to build an object file
FormatVersionChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FormatVersionChunk.cpp.o
.PHONY : FormatVersionChunk.cpp.o

FormatVersionChunk.i: FormatVersionChunk.cpp.i
.PHONY : FormatVersionChunk.i

# target to preprocess a source file
FormatVersionChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FormatVersionChunk.cpp.i
.PHONY : FormatVersionChunk.cpp.i

FormatVersionChunk.s: FormatVersionChunk.cpp.s
.PHONY : FormatVersionChunk.s

# target to generate assembly for a file
FormatVersionChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/FormatVersionChunk.cpp.s
.PHONY : FormatVersionChunk.cpp.s

SoundDataChunk.o: SoundDataChunk.cpp.o
.PHONY : SoundDataChunk.o

# target to build an object file
SoundDataChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/SoundDataChunk.cpp.o
.PHONY : SoundDataChunk.cpp.o

SoundDataChunk.i: SoundDataChunk.cpp.i
.PHONY : SoundDataChunk.i

# target to preprocess a source file
SoundDataChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/SoundDataChunk.cpp.i
.PHONY : SoundDataChunk.cpp.i

SoundDataChunk.s: SoundDataChunk.cpp.s
.PHONY : SoundDataChunk.s

# target to generate assembly for a file
SoundDataChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/SoundDataChunk.cpp.s
.PHONY : SoundDataChunk.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/abledecoder.dir/build.make CMakeFiles/abledecoder.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... abledecoder"
	@echo "... AbleChunk.o"
	@echo "... AbleChunk.i"
	@echo "... AbleChunk.s"
	@echo "... CommonChunk.o"
	@echo "... CommonChunk.i"
	@echo "... CommonChunk.s"
	@echo "... FileChunk.o"
	@echo "... FileChunk.i"
	@echo "... FileChunk.s"
	@echo "... FormChunk.o"
	@echo "... FormChunk.i"
	@echo "... FormChunk.s"
	@echo "... FormatVersionChunk.o"
	@echo "... FormatVersionChunk.i"
	@echo "... FormatVersionChunk.s"
	@echo "... SoundDataChunk.o"
	@echo "... SoundDataChunk.i"
	@echo "... SoundDataChunk.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

